org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.248
loader_version_range=[4,)

mod_id=reopenedmodularturrets
mod_name=Reopened Modular Turrets
mod_license=MIT
mod_version=5.0.0-alpha
mod_group_id=com.ommods.reopenedmodularturrets

jei_version=19.27.0.340
emi_version=1.1.24+1.21.1
powah_file_id=6074034
powah_project_id=633483
