org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.67

mod_id=reopenedmodularturrets
mod_name=Reopened Modular Turrets
mod_license=MIT
mod_version=5.0.0-alpha
mod_group_id=com.ommods.reopenedmodularturrets

jei_version=30.26.0.186
