package com.ommods.reopenedmodularturrets.config;

import net.neoforged.neoforge.common.ModConfigSpec;

public final class ModConfig {
    private static final ModConfigSpec.Builder BUILDER = new ModConfigSpec.Builder();

    public static final ModConfigSpec.BooleanValue ATTACK_MOBS = BUILDER
            .comment("Allow turrets to attack hostile mobs")
            .define("targeting.attackMobs", true);

    public static final ModConfigSpec.BooleanValue ATTACK_PLAYERS = BUILDER
            .comment("Allow turrets to attack players")
            .define("targeting.attackPlayers", false);

    public static final ModConfigSpec.BooleanValue ATTACK_NEUTRAL = BUILDER
            .comment("Allow turrets to attack neutral mobs (animals)")
            .define("targeting.attackNeutral", false);

    public static final ModConfigSpec.IntValue GUN_RANGE = BUILDER
            .comment("Gun turret range in blocks")
            .defineInRange("turrets.gun.range", 16, 1, 64);

    public static final ModConfigSpec.IntValue GUN_DAMAGE = BUILDER
            .comment("Gun turret damage per shot")
            .defineInRange("turrets.gun.damage", 4, 1, 100);

    public static final ModConfigSpec.IntValue GUN_ENERGY_PER_SHOT = BUILDER
            .comment("Energy consumed per gun shot")
            .defineInRange("turrets.gun.energyPerShot", 80, 1, 10000);

    public static final ModConfigSpec.IntValue GUN_COOLDOWN = BUILDER
            .comment("Ticks between gun shots")
            .defineInRange("turrets.gun.cooldown", 10, 1, 200);

    public static final ModConfigSpec.IntValue GRENADE_RANGE = BUILDER
            .comment("Grenade turret range in blocks")
            .defineInRange("turrets.grenade.range", 12, 1, 64);

    public static final ModConfigSpec.IntValue GRENADE_DAMAGE = BUILDER
            .comment("Grenade explosion damage")
            .defineInRange("turrets.grenade.damage", 6, 1, 100);

    public static final ModConfigSpec.IntValue GRENADE_ENERGY_PER_SHOT = BUILDER
            .comment("Energy consumed per grenade shot")
            .defineInRange("turrets.grenade.energyPerShot", 120, 1, 10000);

    public static final ModConfigSpec.IntValue GRENADE_COOLDOWN = BUILDER
            .comment("Ticks between grenade shots")
            .defineInRange("turrets.grenade.cooldown", 40, 1, 200);

    public static final ModConfigSpec.IntValue SOLAR_GENERATION = BUILDER
            .comment("FE/t generated by solar addon in daylight")
            .defineInRange("addons.solar.generation", 4, 0, 1000);

    public static final ModConfigSpec.IntValue REDSTONE_REACTOR_GENERATION = BUILDER
            .comment("FE/t generated by redstone reactor while redstone dust is available in ammo slots")
            .defineInRange("addons.redstoneReactor.generation", 4, 0, 1000);

    public static final ModConfigSpec.IntValue REDSTONE_REACTOR_CONSUME_INTERVAL = BUILDER
            .comment("Ticks between consuming one redstone dust from ammo slots")
            .defineInRange("addons.redstoneReactor.consumeInterval", 20, 1, 200);

    public static final ModConfigSpec.IntValue UPGRADE_MAX_STACK = BUILDER
            .comment("Maximum stack size per upgrade slot")
            .defineInRange("upgrades.maxStackSize", 4, 1, 64);

    public static final ModConfigSpec.IntValue LEVER_GENERATION = BUILDER
            .comment("FE generated per crank use on tier-1 bases")
            .defineInRange("infrastructure.lever.generation", 100, 1, 10000);

    public static final ModConfigSpec.IntValue TARGETING_DOWN_RANGE = BUILDER
            .comment("Additional blocks below the turret origin to search for targets")
            .defineInRange("targeting.downRange", 4, 0, 32);

    public static final ModConfigSpec.IntValue TARGETING_MAX_SEE_THROUGH = BUILDER
            .comment("Maximum non-solid blocks a turret can see through when checking line of sight")
            .defineInRange("targeting.maxSeeThroughBlocks", 100, 0, 256);

    public static final ModConfigSpec SPEC = BUILDER.build();

    private ModConfig() {}
}
